// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxckwCxkX9DXX9fezKmA2Xhr5zxcoELRo',
    appId: '1:811115689829:ios:4b8735edc5ed95e529138c',
    messagingSenderId: '811115689829',
    projectId: 'dvove-a907b',
    storageBucket: 'dvove-a907b.firebasestorage.app',
    iosBundleId: 'com.example.countyConnect',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQmvIKPusOJAVi-j_dH-6SCV453SWnEcg',
    appId: '1:811115689829:android:6346387a351b49eb29138c',
    messagingSenderId: '811115689829',
    projectId: 'dvove-a907b',
    storageBucket: 'dvove-a907b.firebasestorage.app',
  );

}